/**
 * Created by ling xue on 15-9-8.
 */

/**
 * PROD STATUS
 */
var PROD_STATUS_ACTIVE = 1;
var PROD_STATUS_ACTIVE_NO = 0;

var PROD_STATUS = 1;
var PROD_STATUS_NO = 0;

var PROD_TYPE_STATUS = 1;
var PROD_TYPE_STATUS_NO = 0;


/**
 * USER STATUS
 */
var USER_STATUS_ACTIVE = 1 ;
var USER_STATUS_NOT_ACTIVE = 0;

/**
 * Image Type
 */
var IMAGE_TYPE_BRAND = 1 ;
var IMAGE_TYPE_AUTO = 2;

/**
 * ADMIN USER STATUS
 */
var ADMIN_USER_STATUS_ACTIVE = 1 ;
var ADMIN_USER_STATUS_NOT_ACTIVE = 0;

/**
 * USER STATUS
 */
var USER_STATUS_ACTIVE = 1 ;
var USER_STATUS_NOT_ACTIVE = 0;

/**
 * User Type
 */
var USER_TYPE_SUPPLIER = 1;
/**
 * AUTO STATUS
 */
var AUTO_STATUS_ACTIVE = 1 ;
var AUTO_STATUS_NOT_ACTIVE = 0;

module.exports = {
    PROD_STATUS_ACTIVE : PROD_STATUS_ACTIVE,
    PROD_STATUS_ACTIVE_NO : PROD_STATUS_ACTIVE_NO,
    PROD_STATUS : PROD_STATUS,
    PROD_STATUS_NO : PROD_STATUS_NO,
    PROD_TYPE_STATUS : PROD_TYPE_STATUS,
    PROD_TYPE_STATUS_NO : PROD_TYPE_STATUS_NO,
    USER_STATUS_ACTIVE : USER_STATUS_ACTIVE ,
    USER_STATUS_NOT_ACTIVE : USER_STATUS_NOT_ACTIVE ,
    ADMIN_USER_STATUS_ACTIVE : ADMIN_USER_STATUS_ACTIVE ,
    ADMIN_USER_STATUS_NOT_ACTIVE : ADMIN_USER_STATUS_NOT_ACTIVE ,
    IMAGE_TYPE_BRAND : IMAGE_TYPE_BRAND ,
    IMAGE_TYPE_AUTO : IMAGE_TYPE_AUTO ,
    AUTO_STATUS_ACTIVE : AUTO_STATUS_ACTIVE ,
    AUTO_STATUS_NOT_ACTIVE : AUTO_STATUS_NOT_ACTIVE ,
    USER_STATUS_ACTIVE : USER_STATUS_ACTIVE ,
    USER_STATUS_NOT_ACTIVE : USER_STATUS_NOT_ACTIVE ,
    USER_TYPE_SUPPLIER : USER_TYPE_SUPPLIER
}